{
 "title": "Eradani Outbound Calls Stats",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nodejs_process_cpu_usage_percentage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Used, Mb",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(nodejs_process_memory_heap_used_bytes)/1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Per Command counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(command_Num_Of_Command_Calls)"
    }
   ]
  },
  {
   "title": "Total Error calls",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(command_Num_Of_Command_Errors)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Success calls",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(command_all_success_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests/Error/Success",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(command_all_request_total)", "legendFormat": "Request Total" },
    { "expr": "sum(command_all_errors_total)", "legendFormat": "Error Total" },
    { "expr": "sum(command_all_success_total)", "legendFormat": "Success Total" }
   ]
  },
  {
   "title": "Top 3 command calls",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, sum(command_Num_Of_Command_Calls) by (command))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 3 command calls",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, sum(command_Num_Of_Command_Calls) by (command))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 3 error command calls",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, sum(command_Num_Of_Command_Errors) by (command))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 3 error command calls",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, sum(command_Num_Of_Command_Errors) by (command))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 3 success command calls",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, sum(command_Num_Of_Command_Success) by (command))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 3 success command calls",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, sum(command_Num_Of_Command_Success) by (command))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "All commands counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "% Error ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(command_all_errors_total) / sum(command_all_request_total) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "( sum(irate(command_request_duration_milliseconds_bucket{le=\"5\"}[1m])) / sum(irate(command_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 5ms (%)"
    },
    {
     "expr": "( sum(irate(command_request_duration_milliseconds_bucket{le=\"10\"}[1m])) / sum(irate(command_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 10ms (%)"
    },
    {
     "expr": "( sum(irate(command_request_duration_milliseconds_bucket{le=\"50\"}[1m])) / sum(irate(command_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 50ms (%)"
    },
    {
     "expr": "( sum(irate(command_request_duration_milliseconds_bucket{le=\"100\"}[1m])) / sum(irate(command_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 100ms (%)"
    }
   ]
  },
  {
   "title": "Command Request ",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum(command_All_Request_Duration_Seconds_bucket) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } }
 ]
}