import eradaniConnect from '@eradani-inc/eradani-connect';
// XXX import configService from 'config';
import { JSONObject } from 'src/types';
// XXX const config = configService.get().eradaniConnect.native;

export default new eradaniConnect.run.Sql(
    `SELECT 
	WOLFIASP.OLFILE5.TRIP.DIV##T,
	WOLFIASP.OLFILE5.STOP.SEQNOST,
	WOLFIASP.OLFILE5.TRIP.TRIP#T,
	WOLFIASP.OLFILE5.ORDR.ORDEROR,
	WOLFIASP.OLFILE5.TRIP.TRIDTT,
	WOLFIASP.OLFILE5.ORDR.SHPDTOR,
	WOLFIASP.OLFILE5.ORDR.TYPEOOR,
	WOLFIASP.OLFILE5.STOP.LOCCDST,
	WOLFIASP.OLFILE5.LOCT.VNAME8,
	WOLFIASP.OLFILE5.LOCT.CITYV8,
	WOLFIASP.OLFILE5.LOCT.STATV8,
	WOLFIASP.OLFILE5.STOP.WEIGTST,
	WOLFIASP.OLFILE5.STOP.PIECEST,
	WOLFIASP.OLFILE5.ORDR.MANF#OR,
	WOLFIASP.OLFILE5.ORDR.ACCT#OR,
	WOLFIASP.OLFILE5.BLHD.CONS#H,
	WOLFIASP.OLFILE5.BLHD.ACCT#H,
	WOLFIASP.OLFILE5.BLHD.COBLTH,
	WOLFIASP.OLFILE5.TRIP.TTYPET,
	WOLFIASP.OLFILE5.DRIV.GROUPDR,
        WOLFIASP.OLFILE5.ORDR.CONCDOR,
        WOLFIASP.OLFILE5.STOP.ORDERST,
        WOLFIASP.OLFILE5.STOP.REFNOST,
        WOLFIASP.OLFILE5.LOCT.BLTOCD8,
        WOLFIASP.OLFILE5.MOVE.PRO##N,
        WOLFIASP.OLFILE5.MOVE.MOVE#N,
        WOLFIASP.OLFILE5.ORDR.REFNOOR,
        WOLFIASP.OLFILE5.ORDR.MAST#OR,
        WOLFIASP.OLFILE5.DRIV.ENAMEDR
FROM 
	WOLFIASP.OLFILE5.TRIP
	LEFT OUTER JOIN WOLFIASP.OLFILE5.ORDR
	ON 
		WOLFIASP.OLFILE5.TRIP.TRIP#T = WOLFIASP.OLFILE5.ORDR.TRIP#OR
	LEFT OUTER JOIN WOLFIASP.OLFILE5.STOP
	ON 
		WOLFIASP.OLFILE5.ORDR.ORDEROR = WOLFIASP.OLFILE5.STOP.ORDERST
	LEFT OUTER JOIN WOLFIASP.OLFILE5.LOCT
	ON 
		WOLFIASP.OLFILE5.STOP.LOCCDST = WOLFIASP.OLFILE5.LOCT.LOCID8
	LEFT OUTER JOIN WOLFIASP.OLFILE5.MOVE
	ON 
		WOLFIASP.OLFILE5.ORDR.PRO##OR = WOLFIASP.OLFILE5.MOVE.PRO##N
	LEFT OUTER JOIN WOLFIASP.OLFILE5.BLHD
	ON 
		WOLFIASP.OLFILE5.ORDR.PRO##OR = WOLFIASP.OLFILE5.BLHD.PRO##H
	LEFT OUTER JOIN WOLFIASP.OLFILE5.DRIV
	ON 
		WOLFIASP.OLFILE5.ORDR.DRVCDOR = WOLFIASP.OLFILE5.DRIV.EMPNODR
	 
WHERE 
	WOLFIASP.OLFILE5.TRIP.DIV##T IN( '75', '75M', '77', '77W' )
	AND WOLFIASP.OLFILE5.ORDR.TYPEOOR IN( 'LD', 'LP' )
	AND WOLFIASP.OLFILE5.STOP.SEQNOST <> 90
	and shpdtor > ?`,
    {
        params: [
            {
                name: 'fromDate'
            }
        ]
    }
);

/**
 * Input Structure for SQLTemplate. Includes detailed field information such as
 * field length, format, numerical precision, and default values.
 */
export interface SQLTemplateInputLTLWGT {
    /**
     * @description From Date
     */
    fromDate: number | string;
}
/**
 * Structure of records outputted by SQLTemplate SQL query
 *
 * @todo For future development, you may want to add the remaining SQLTemplate output fields here.
 */
export type SQLTemplateOutputRecord = JSONObject;

/**
 * Output Structure for SQLTemplate SQL query. This is an Array of
 * [[SQLTemplateOutputRecord]] elements.
 */
export interface SQLTemplateOutputLTLWGT extends Array<SQLTemplateOutputRecord> {}
