import eradaniConnect from '@eradani-inc/eradani-connect';
// XXX import configService from 'config';
import { JSONObject } from 'src/types';
// XXX const config = configService.get().eradaniConnect.native;

export default new eradaniConnect.run.Sql(
    `SELECT 
	WOLFIASP.OLFILE5.TRIP.DIV##T,
	WOLFIASP.OLFILE5.TRIP.TRIP#T,
	WOLFIASP.OLFILE5.ORDR.ORDEROR,
	WOLFIASP.OLFILE5.ORDR.TYPEOOR,
	WOLFIASP.OLFILE5.STOP.SEQNOST,
	WOLFIASP.OLFILE5.STOP.REASNST,
	WOLFIASP.OLFILE5.ORDR.SHPDTOR,
	WOLFIASP.OLFILE5.ORDR.SHPCDOR,
	WOLFIASP.OLFILE5.LOCT.VNAME8,
	WOLFIASP.OLFILE5.LOCT.CITYV8,
	WOLFIASP.OLFILE5.LOCT.STATV8,
	WOLFIASP.OLFILE5.LOCT.ZIPCV8,
	WOLFIASP.OLFILE5.ORDR.CONCDOR,
	WOLFIASP.OLFILE5.ORDR.CONSTOR,
	WOLFIASP.OLFILE5.ORDR.CONCTOR,
	WOLFIASP.OLFILE5.ORDR.DUEDTOR,
	WOLFIASP.OLFILE5.ORDR.DUETMOR,
	WOLFIASP.OLFILE5.ORDR.ACCT#OR,
	WOLFIASP.OLFILE5.ORDR.PRO##OR,
	WOLFIASP.OLFILE5.ORDR.DLWGTOR,
	WOLFIASP.OLFILE5.ORDR.DLCTNOR,
	WOLFIASP.OLFILE5.STOP.ARVDTST,
	WOLFIASP.OLFILE5.STOP.ARVTMST,
	WOLFIASP.OLFILE5.STOP.STRDTST,
	WOLFIASP.OLFILE5.STOP.STRTMST,
	WOLFIASP.OLFILE5.STOP.DEPDTST,
	WOLFIASP.OLFILE5.STOP.DEPTMST,
	WOLFIASP.OLFILE5.STOP.ELMINST,
	WOLFIASP.OLFILE5.STOP.LATERST,
	WOLFIASP.OLFILE5.STOP.DUETMST,
	WOLFIASP.OLFILE5.CUST.NAMEAA,
	WOLFIASP.OLFILE5.ORDR.DIV#BOR,
	WOLFIASP.OLFILE5.ORDR.COMP#OR,
	WOLFIASP.OLFILE5.ORDR.REVENOR,
	WOLFIASP.OLFILE5.BLHD.TOTALH,
	WOLFIASP.OLFILE5.ORDR.DRVCDOR,
	WOLFIASP.OLFILE5.DRIV.TYPCDDR,
	WOLFIASP.OLFILE5.TRIP.WEIGHT,
	WOLFIASP.OLFILE5.CUST.ACCT#A,
	WOLFIASP.OLFILE5.BLHD.CONS#H,
	WOLFIASP.OLFILE5.BLHD.COBLTH,
	WOLFIASP.OLFILE5.BLHD.ACCT#H,
	WOLFIASP.OLFILE5.TRIP.TTYPET,
	WOLFIASP.OLFILE5.DRIV.GROUPDR,
        WOLFIASP.OLFILE5.DRIV.ENAMEDR
FROM 
	WOLFIASP.OLFILE5.TRIP
	LEFT OUTER JOIN WOLFIASP.OLFILE5.ORDR
	ON 
		WOLFIASP.OLFILE5.TRIP.TRIP#T = WOLFIASP.OLFILE5.ORDR.TRIP#OR
	LEFT OUTER JOIN WOLFIASP.OLFILE5.STOP
	ON 
		WOLFIASP.OLFILE5.ORDR.ORDEROR = WOLFIASP.OLFILE5.STOP.ORDERST
	LEFT OUTER JOIN WOLFIASP.OLFILE5.LOCT
	ON 
		WOLFIASP.OLFILE5.STOP.LOCCDST = WOLFIASP.OLFILE5.LOCT.LOCID8
	LEFT OUTER JOIN WOLFIASP.OLFILE5.CUST
	ON 
		WOLFIASP.OLFILE5.ORDR.ACCT#OR = WOLFIASP.OLFILE5.CUST.ACCT#A
	LEFT OUTER JOIN WOLFIASP.OLFILE5.BLHD
	ON 
		WOLFIASP.OLFILE5.ORDR.PRO##OR = WOLFIASP.OLFILE5.BLHD.PRO##H
	LEFT OUTER JOIN WOLFIASP.OLFILE5.DRIV
	ON 
		WOLFIASP.OLFILE5.ORDR.DRVCDOR = WOLFIASP.OLFILE5.DRIV.EMPNODR
	 
WHERE 
	WOLFIASP.OLFILE5.ORDR.SHPDTOR > ?
	AND WOLFIASP.OLFILE5.TRIP.DIV##T IN( '75', '75M', '77', '77W' )
	AND WOLFIASP.OLFILE5.STOP.SEQNOST <> 90
	AND WOLFIASP.OLFILE5.ORDR.TYPEOOR = 'TL'`,
    {
        params: [
            {
                name: 'fromDate'
            }
        ]
    }
);

/**
 * Input Structure for SQLTemplate. Includes detailed field information such as
 * field length, format, numerical precision, and default values.
 */
export interface SQLTemplateInputTLWGT {
    /**
     * @description From Date
     */
    fromDate: number | string;
}
/**
 * Structure of records outputted by SQLTemplate SQL query
 *
 * @todo For future development, you may want to add the remaining SQLTemplate output fields here.
 */
export type SQLTemplateOutputRecord = JSONObject;

/**
 * Output Structure for SQLTemplate SQL query. This is an Array of
 * [[SQLTemplateOutputRecord]] elements.
 */
export interface SQLTemplateOutputTLWGT extends Array<SQLTemplateOutputRecord> {}
