import eradaniConnect from '@eradani-inc/eradani-connect';
// XXX import configService from 'config';
import { JSONObject } from 'src/types';
// XXX const config = configService.get().eradaniConnect.native;

export default new eradaniConnect.run.Sql(
    `SELECT DISTINCT  
	WOLFIASP.OLFILE5.DISP.DIVI#DI,
	WOLFIASP.OLFILE5.CUST.NAMEAA,
	CASE 
		WHEN WOLFIASP.OLFILE5.CUST.ORIGNA = 'IK' OR ( WOLFIASP.OLFILE5.CUST.ORIGNA IS NULL AND WOLFIASP.OLFILE5.LOCT.VNAME8 LIKE '%IKEA%' ) THEN 'IKEA' 
		WHEN WOLFIASP.OLFILE5.CUST.ORIGNA = 'TJ' OR ( WOLFIASP.OLFILE5.CUST.ORIGNA IS NULL AND ( WOLFIASP.OLFILE5.LOCT.VNAME8 LIKE '%HOME GOODS%' OR WOLFIASP.OLFILE5.LOCT.VNAME8 LIKE '%MARMAXX%' ) ) THEN 'TJX' 
		WHEN WOLFIASP.OLFILE5.CUST.ORIGNA = 'VF' OR ( WOLFIASP.OLFILE5.CUST.ORIGNA IS NULL AND ( WOLFIASP.OLFILE5.LOCT.VNAME8 LIKE '%VANS%' OR WOLFIASP.OLFILE5.LOCT.VNAME8 LIKE '%VF%' ) ) THEN 'VF' 
		WHEN WOLFIASP.OLFILE5.CUST.ORIGNA = 'DS' OR ( WOLFIASP.OLFILE5.CUST.ORIGNA IS NULL AND WOLFIASP.OLFILE5.LOCT.VNAME8 LIKE '%DSW%' ) THEN 'DSW' 
		WHEN WOLFIASP.OLFILE5.CUST.ORIGNA = 'TS' OR ( WOLFIASP.OLFILE5.CUST.ORIGNA IS NULL AND WOLFIASP.OLFILE5.LOCT.VNAME8 LIKE '%TARGET%' ) THEN 'TARGET' 
		WHEN WOLFIASP.OLFILE5.CUST.ORIGNA = 'BB' OR ( WOLFIASP.OLFILE5.CUST.ORIGNA IS NULL AND WOLFIASP.OLFILE5.LOCT.VNAME8 LIKE '%BEST BUY%' ) THEN 'BEST BUY' 
		WHEN WOLFIASP.OLFILE5.CUST.ORIGNA = 'DG' OR ( WOLFIASP.OLFILE5.CUST.ORIGNA IS NULL AND WOLFIASP.OLFILE5.LOCT.VNAME8 LIKE '%DOLLAR GENERAL%' ) THEN 'DOLLAR GENERAL' 
		WHEN WOLFIASP.OLFILE5.CUST.ORIGNA = 'RS' OR ( WOLFIASP.OLFILE5.CUST.ORIGNA IS NULL AND WOLFIASP.OLFILE5.LOCT.VNAME8 LIKE '%ROSS%' ) THEN 'ROSS' 
		WHEN WOLFIASP.OLFILE5.CUST.ORIGNA = 'CH' THEN 'CH ROBINSON' 
		WHEN WOLFIASP.OLFILE5.CUST.ORIGNA = 'GP' OR ( ORIGNA IS NULL AND WOLFIASP.OLFILE5.LOCT.VNAME8 LIKE '%GAP%' ) THEN 'GAP' 
		WHEN WOLFIASP.OLFILE5.CUST.ORIGNA = 'NULL' OR WOLFIASP.OLFILE5.CUST.ORIGNA IS NULL THEN 'TERMINAL SHUTTLE' 
		WHEN WOLFIASP.OLFILE5.CUST.ORIGNA = '' THEN 'MISC' 
		ELSE WOLFIASP.OLFILE5.CUST.ORIGNA 
	END AS COLUMN0000,
	WOLFIASP.OLFILE5.CUST.ORIGNA,
	WOLFIASP.OLFILE5.ORDR.TYPEOOR,
	WOLFIASP.OLFILE5.ORDR.ORDEROR,
	WOLFIASP.OLFILE5.ORDR.TRIP#OR,
	WOLFIASP.OLFILE5.LOCT.VNAME8,
	WOLFIASP.OLFILE5.LOCT.CITYV8,
	WOLFIASP.OLFILE5.LOCT.STATV8,
	WOLFIASP.OLFILE5.LOCT.VNAME8,
	WOLFIASP.OLFILE5.LOCT.CITYV8,
	WOLFIASP.OLFILE5.LOCT.STATV8,
	WOLFIASP.OLFILE5.ORDR.STADTOR,
	WOLFIASP.OLFILE5.DRIV.TYPCDDR,
	WOLFIASP.OLFILE5.DRIV.SUBGPDR,
	WOLFIASP.OLFILE5.DRIV.GROUPDR,
	WOLFIASP.OLFILE5.DRIV.ENAMEDR,
	WOLFIASP.OLFILE5.DISP.#LOADDI,
	WOLFIASP.OLFILE5.DISP.#EMPTDI,
	WOLFIASP.OLFILE5.DISP.#LOADDI + WOLFIASP.OLFILE5.DISP.#EMPTDI AS #MILEDI,
	WOLFIASP.OLFILE5.ORDR.STADTOR + ( 7 - DAYOFWEEK( WOLFIASP.OLFILE5.ORDR.STADTOR ) ) DAY AS COLUMN0000_1,
	WOLFIASP.OLFILE5.DISP.DI1DTDI,
	WOLFIASP.OLFILE5.DISP.DI1DTDI + ( 7 - DAYOFWEEK( WOLFIASP.OLFILE5.DISP.DI1DTDI ) ) DAY AS DI1DTDI_1,
	WOLFIASP.OLFILE5.ORDR.ACCT#OR,
	WOLFIASP.OLFILE5.PYDT.GROSSM,
	WOLFIASP.WSFILE2.BLHD.PRO##H,
	WOLFIASP.WSFILE2.BLHD.TOTALH,
	WOLFIASP.OLFILE5.ILXF.ILAMTF,
	WOLFIASP.WSFILE2.ILPH01.AMOUNJ 
FROM 
	WOLFIASP.OLFILE5.ORDR
	LEFT OUTER JOIN WOLFIASP.OLFILE5.DISP
	ON 
		WOLFIASP.OLFILE5.ORDR.ORDEROR = WOLFIASP.OLFILE5.DISP.ORDERDI
	LEFT OUTER JOIN WOLFIASP.OLFILE5.DRIV
	ON 
		WOLFIASP.OLFILE5.DISP.DRIV1DI = WOLFIASP.OLFILE5.DRIV.EMPNODR
	LEFT OUTER JOIN WOLFIASP.OLFILE5.LOCT
	ON 
		WOLFIASP.OLFILE5.ORDR.SHPCDOR = WOLFIASP.OLFILE5.LOCT.LOCID8
	LEFT OUTER JOIN WOLFIASP.WSFILE2.BLHD
	ON 
		WOLFIASP.OLFILE5.ORDR.ORDEROR = WOLFIASP.WSFILE2.BLHD.ORDERH
	LEFT OUTER JOIN WOLFIASP.OLFILE5.CUST
	ON 
		WOLFIASP.WSFILE2.BLHD.ACCT#H = WOLFIASP.OLFILE5.CUST.ACCT#A
	LEFT OUTER JOIN WOLFIASP.OLFILE5.PYDT
	ON 
		WOLFIASP.OLFILE5.ORDR.ORDEROR = WOLFIASP.OLFILE5.PYDT.ORDR#M
	LEFT OUTER JOIN WOLFIASP.OLFILE5.ILXF
	ON 
		WOLFIASP.OLFILE5.ORDR.PRO##OR = WOLFIASP.OLFILE5.ILXF.PRO##F
	LEFT OUTER JOIN WOLFIASP.WSFILE2.ILPH01
	ON 
		WOLFIASP.OLFILE5.ORDR.PRO##OR = WOLFIASP.WSFILE2.ILPH01.PRO##J
	 
WHERE 
	WOLFIASP.OLFILE5.DISP.DISP#DI <> 0
	AND WOLFIASP.OLFILE5.DISP.DIVI#DI IN( '75', '75M', '75S', '77', '77W' )
	AND WOLFIASP.OLFILE5.DISP.DI1DTDI between ? and ?
ORDER BY 
	21`,
    {
        params: [
            {
                name: 'fromDate'
            },
            {
                name: 'toDate'
            }
        ]
    }
);

export interface SQLTemplateInputSUPERS {
    /**
     * @description From Date
     */
    fromDate: number | string;
    /**
     * @description To Date
     */
    toDate: number | string;
}

/**
 * Structure of records outputted by SQLTemplate SQL query
 *
 * @todo For future development, you may want to add the remaining SQLTemplate output fields here.
 */
export type SQLTemplateOutputRecord = JSONObject;

/**
 * Output Structure for SQLTemplate SQL query. This is an Array of
 * [[SQLTemplateOutputRecord]] elements.
 */
export interface SQLTemplateOutputSUPERS extends Array<SQLTemplateOutputRecord> {}
